- include/pluginplay/module_base.hpp
- include/pluginplay/module_manager.hpp
- src/pluginplay/detail_/module_manager_pimpl.hpp
- tests/pluginplay/module_base.cpp
- tests/pluginplay/test_main.cpp
Required change after recent [PR](https://github.com/NWChemEx-Project/ParallelZone/commit/7ad52615e201acb5554ccbfe8f3c73e88762c1e3) in ParallelZone.
> Fix for the runtime filename

- include/pluginplay/any/any_field.hpp
- tests/pluginplay/any/any_field.cpp
- tests/pluginplay/cache/uuid_mapper.cpp
This PR adds some more unit tests aimed at ruling out why NWChemEx won't build with GCC 9. All of them pass with GCC 9, so I'm still on the hunt for the bug...
This PR also removes some unused code from `AnyField`.
> Unit Tests

- tests/pluginplay/cache/database/native.cpp
- tests/pluginplay/cache/database/serialized.cpp
Fixes a potential failure in the tests when these values are not defaulted.
> Test Bug Fix

- src/pluginplay/cache/database/native.ipp
- src/pluginplay/cache/database/serialized.ipp
- src/pluginplay/cache/database/transposer.ipp
- tests/pluginplay/cache/uuid_mapper.cpp
This addresses some of the new cache to try to reduce some of the observed slowdown mentioned in #259. I'm not convinced it covers all potential sources of the slowdown, but it does reduce it.
> Address some of cache slowdown

- include/pluginplay/property_type/field_tuple.hpp
> Fixes Clang Error

- .github/workflows/add_licenses.yaml
- .github/workflows/c-cpp.yaml
- .github/workflows/deploy_docs.yaml
- .github/workflows/format.yaml
- .github/workflows/test_docs.yaml
> YAML conversion

- .github/.licenserc.yaml
- .github/workflows/tag_and_release.yaml
- CMakeLists.txt
Added automate versioning for PluginPlay
> Added automate versioning (Skipping release)

- .github/workflows/c-cpp.yaml
- tests/pluginplay/detail_/any_wrapper.cpp
- In the Testing Phase.
- Added parallel GCC and Clang build support.
> Parallel build for GCC and Clang

- .github/workflows/c-cpp.yaml
**PR Type**
- [✓ ] Breaking change
This PR will enable the REPO to be built using ninja.
Anything not related to ninja-enabled build.
- [API](https://nwchemex-project.github.io/.github/documenting/writing_api_documentation.html)
- [User](https://nwchemex-project.github.io/.github/documenting/writing_tutorials.html)
- [Design](https://nwchemex-project.github.io/.github/documenting/writing_design_documentation.html)
- [Developer](https://nwchemex-project.github.io/.github/documenting/writing_developer_documentation.html)
- [Unit](https://nwchemex-project.github.io/.github/testing/unit.html)
- [Integration](https://nwchemex-project.github.io/.github/testing/integration.html)
- [Performance](https://nwchemex-project.github.io/.github/test …
> Ninja enabled build applied

- .github/workflows/tag_and_release.yaml
**PR Type**
Updated automate versioning with following changes:
-> Changed reference to master branch for the template workflow.
-> Changed token to TAG_TOKEN
Anything not related to automated versioning.
- [API](https://nwchemex-project.github.io/.github/documenting/writing_api_documentation.html)
- [User](https://nwchemex-project.github.io/.github/documenting/writing_tutorials.html)
- [Design](https://nwchemex-project.github.io/.github/documenting/writing_design_documentation.html)
- [Developer](https://nwchemex-project.github.io/.github/documenting/writing_developer_documentation.html)
- [Unit](https://nwchemex-project.github.io/.github/testing/unit.html)
- [Integration](https://nwchemex-project.github.io/.github/testing/integratio …
> Automated Versioning Update

- .github/workflows/c-cpp.yaml
- CMakeLists.txt
**PR Type**
- [API](https://nwchemex-project.github.io/.github/documenting/writing_api_documentation.html)
- [User](https://nwchemex-project.github.io/.github/documenting/writing_tutorials.html)
- [Design](https://nwchemex-project.github.io/.github/documenting/writing_design_documentation.html)
- [Developer](https://nwchemex-project.github.io/.github/documenting/writing_developer_documentation.html)
- [Unit](https://nwchemex-project.github.io/.github/testing/unit.html)
- [Integration](https://nwchemex-project.github.io/.github/testing/integration.html)
- [Performance](https://nwchemex-project.github.io/.github/testing/performance.html)
- [C++](https://nwchemex-project.github.io/.github/coding/cxx/cxx_conventions.html)
- …
> Switch to CMaize

- CMakeLists.txt
**PR Type**
Some changes to `CMakeLists.txt` that were missed.
- [API](https://nwchemex-project.github.io/.github/documenting/writing_api_documentation.html)
- [User](https://nwchemex-project.github.io/.github/documenting/writing_tutorials.html)
- [Design](https://nwchemex-project.github.io/.github/documenting/writing_design_documentation.html)
- [Developer](https://nwchemex-project.github.io/.github/documenting/writing_developer_documentation.html)
- [Unit](https://nwchemex-project.github.io/.github/testing/unit.html)
- [Integration](https://nwchemex-project.github.io/.github/testing/integration.html)
- [Performance](https://nwchemex-project.github.io/.github/testing/performance.html)
- …
> Missed CMaize changes

- .github/workflows/c-cpp.yaml
**PR Type**
This PR enables installing libfort from cache.
Anything not related to caching libfort.
**TODOs**
Nothing.
> Applied caching for libfort

- CMakeLists.txt
**PR Type**
Use the version info from NWXCMake.
> Use NWXCMake version info

- .github/workflows/build_test_release.yaml
**PR Type**
Change the branch name of the action of build_base to master.
**TODOs**
> change the branch name of the action of build_base

- .github/workflows/build_test_release-manual.yaml
**PR Type**
When the build/test/release workflow is invoked manually, the stable release images should be updated, otherwise this workflow will not have effect on downstream repos. Whether this "stable" release images break downstream repos or not should be checked. 
**TODOs**
> Force to update stable release images in build_test_release-manual.yaml

- src/pluginplay/printing/detail_/print_inputs.cpp
- src/pluginplay/printing/detail_/print_results.cpp
- src/pluginplay/printing/detail_/print_submodules.cpp
**PR Type**
Change out the libfort tables to ensure proper printing.
> Use utf8_tables

- .github/actions/generate_module_docs/action.yaml
**PR Type**
Fix the input name in the module dox action.
> Module Dox Action Fix

- .github/workflows/pull_request.yaml
- CMakeLists.txt
- cmake/get_nwx_cmake.cmake
- tests/python/unit_tests/tox.ini
**PR Type**
This PR refactors the `CMakeLists.txt` file to showcase CMaize features (it's going to be used as the poster child for the upcoming CMaize paper). It can't be merged until NWChemEx/NWXCMake#36 is merged.
N/A
> Cmaize refactor

- .github/workflows/pull_request.yaml
- CMakeLists.txt
**PR Type**
Debugging an issue in CI when the library version is acquired from git. The workflow changes here will be ported to `NWChemEx/.github` once this is solved, then this will simplify to just the changes to the `CMakeLists.txt`,
> Reconcile library version from Git with CI

- tests/python/doc_snippets/export_pluginplay_examples.cpp
**PR Type**
Small change in reference to this [comment](https://github.com/NWChemEx/PluginPlay/pull/333#discussion_r1456079900).
> Use `EXPORT_PLUGIN` in `pluginplay_examples`

- CMakeLists.txt
> patch for NWXCMake#41

- docs/source/background/architecture.rst
- docs/source/background/statement_of_need.rst
- docs/source/developer/design/call_graph.rst
- docs/source/developer/design/field.rst
- docs/source/developer/design/module.rst
- docs/source/developer/design/module_manager.rst
- docs/source/tutorials/modules/basics.rst
**Description**
Some fixes for errors I noticed in the documentation.
> Documentation Patching

- include/pluginplay/cache/module_cache.hpp
- include/pluginplay/cache/module_manager_cache.hpp
- include/pluginplay/fields/bounds_checking/print_bounds.hpp
- include/pluginplay/fields/module_input.ipp
- include/pluginplay/fields/module_result.ipp
- include/pluginplay/module.hpp
- include/pluginplay/module_manager.hpp
- include/pluginplay/submodule_request.hpp
- src/pluginplay/detail_/module_manager_pimpl.hpp
- src/pluginplay/fields/detail_/module_result_pimpl.hpp
- src/python/export_module_manager.cpp
- tests/cxx/doc_snippets/modules.hpp
- tests/cxx/doc_snippets/templated_coulombs_law.cpp
- tests/cxx/doc_snippets/test_tutorial_module_documents.cpp
- tests/cxx/unit_tests/pluginplay/any/any_field.cpp
- tests/cxx/unit_tests/pluginplay/any/detail_/any_field_wrapper_traits.cpp
- tests/cxx/unit_tests/pluginplay/cache/database/value_proxy_mapper.cpp
- tests/cxx/unit_tests/pluginplay/cache/uuid_mapper.cpp
- tests/cxx/unit_tests/pluginplay/detail_/module_pimpl.cpp
- tests/cxx/unit_tests/pluginplay/examples/lambda_module.cpp
- tests/cxx/unit_tests/pluginplay/examples/load_modules.hpp
- tests/cxx/unit_tests/pluginplay/examples/workflow.hpp
- tests/cxx/unit_tests/pluginplay/examples/writing_a_module.hpp
- tests/cxx/unit_tests/pluginplay/module.cpp
- tests/cxx/unit_tests/pluginplay/module_manager.cpp
- tests/cxx/unit_tests/pluginplay/printing/detail_/print_inputs.cpp
- tests/cxx/unit_tests/pluginplay/printing/document_module.cpp
**Is this pull request associated with an issue(s)?**
No
**Description**
Removes all warnings in compilation.
> `-Wall` Compliant

- CMakeLists.txt
- include/pluginplay/property_type/property_type_impl.hpp
- tests/cxx/regression_tests/issue_350.cpp
- tests/cxx/regression_tests/main.cpp
**Is this pull request associated with an issue(s)?**
Fixes #350
**Description**
Bug fix, also starts a regression test suite.
**TODOs**
R2g.
> fixes issue 350
